-- Create produk_bahan table (many-to-many relation)
CREATE TABLE "produkBahan" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "produkId" BIGINT NOT NULL,
    "bahanId" BIGINT NOT NULL,
    "quantity" DECIMAL(12,4),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "produkBahan_pkey" PRIMARY KEY ("id")
);

-- Create indexes
CREATE INDEX "produkBahan_produkId_idx" ON "produkBahan"("produkId");
CREATE INDEX "produkBahan_bahanId_idx" ON "produkBahan"("bahanId");

-- Create unique constraint for produk_bahan
ALTER TABLE "produkBahan" ADD CONSTRAINT "produkBahan_produkId_bahanId_key" UNIQUE ("produkId", "bahanId");

-- Add foreign key constraints
ALTER TABLE "produkBahan" ADD CONSTRAINT "produkBahan_produkId_fkey" FOREIGN KEY ("produkId") REFERENCES "produk"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "produkBahan" ADD CONSTRAINT "produkBahan_bahanId_fkey" FOREIGN KEY ("bahanId") REFERENCES "bahan"("id") ON DELETE CASCADE ON UPDATE CASCADE;
