-- Create produk table
CREATE TABLE "produk" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "namaproduk" VARCHAR(255) NOT NULL,
    "rated" VARCHAR(100),
    "produk1" TEXT,
    "produk2" TEXT,
    "produk3" TEXT,
    "stokproduk" VARCHAR(50),
    "createdby" VARCHAR(100),
    "createdat" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "updatedat" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "produk_pkey" PRIMARY KEY ("id")
);

-- Create produk_snr18_kai table (many-to-many relation)
CREATE TABLE "produkSnr18Kai" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "produkId" BIGINT NOT NULL,
    "snr18KaiId" BIGINT NOT NULL,
    "quantity" DECIMAL(12,4),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "produkSnr18Kai_pkey" PRIMARY KEY ("id")
);

-- Create indexes
CREATE INDEX "idx_produk_nama" ON "produk"("namaproduk");
CREATE INDEX "produkSnr18Kai_produkId_idx" ON "produkSnr18Kai"("produkId");
CREATE INDEX "produkSnr18Kai_snr18KaiId_idx" ON "produkSnr18Kai"("snr18KaiId");

-- Create unique constraint for produk_snr18_kai
ALTER TABLE "produkSnr18Kai" ADD CONSTRAINT "produkSnr18Kai_produkId_snr18KaiId_key" UNIQUE ("produkId", "snr18KaiId");

-- Add foreign key constraints
ALTER TABLE "produkSnr18Kai" ADD CONSTRAINT "produkSnr18Kai_produkId_fkey" FOREIGN KEY ("produkId") REFERENCES "produk"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "produkSnr18Kai" ADD CONSTRAINT "produkSnr18Kai_snr18KaiId_fkey" FOREIGN KEY ("snr18KaiId") REFERENCES "snr18_kai"("id") ON DELETE CASCADE ON UPDATE CASCADE;
